import { FlatCompat } from '@eslint/eslintrc'

/**
 * Flat config, because ESLint 9 dropped `.eslintrc` and `next lint` is
 * deprecated in Next 15. Before this file existed, `npm run lint` ran
 * `next lint`, found no config, and dropped into an interactive
 * "How would you like to configure ESLint?" prompt — so the script hung
 * forever in a terminal and in CI, while CLAUDE.md advertised it as working.
 * `package.json` now calls `eslint` directly.
 *
 * `eslint-config-next` 15.5.9 still ships only the eslintrc-shaped configs
 * (`core-web-vitals.js`, `typescript.js`), so `FlatCompat` is what translates
 * them. Drop it once that package exports a flat config of its own.
 */
const compat = new FlatCompat({ baseDirectory: import.meta.dirname })

export default [
  {
    // Build output, vendored code, and the crawler — a separate project with
    // its own repo and its own tooling, which this one must never write to.
    // `bandincc-crawler/coy123.github.io/` is a stale nested copy of this very
    // repo, so linting it would report hundreds of findings about months-old
    // code that cannot be fixed from here.
    ignores: [
      '.next/**',
      'out/**',
      'dist/**',
      'node_modules/**',
      'bandincc-crawler/**',
      'stripe-worker/node_modules/**',
      'public/service-worker.js',
      // Regenerated by every `next build`; its triple-slash references are
      // Next's own and are not ours to restyle.
      'next-env.d.ts',
    ],
  },

  ...compat.extends('next/core-web-vitals', 'next/typescript'),

  {
    rules: {
      // `<img>` is deliberate and site-wide: every crest is an external
      // Wikimedia URL, nothing imports `next/image`, and `next.config.mjs`
      // carries no `images` config as a result. See "Image Strategy" in
      // CLAUDE.md. Without this the rule fires on essentially every component
      // that renders a bando.
      '@next/next/no-img-element': 'off',
    },
  },

  {
    // A config file whose whole job is to export one object has nothing to name
    // it after, and every tool in this repo expects the default export.
    files: ['*.config.mjs', '*.config.ts'],
    rules: { 'import/no-anonymous-default-export': 'off' },
  },

  {
    // The Cypress specs and the browser-less tests are excluded from
    // `tsconfig.json`, run under different globals, and are not part of the
    // shipped bundle. Lint them for real mistakes, not for app-shaped rules.
    files: ['cypress/**/*.ts', 'test/**/*.ts', 'scripts/**/*.mjs', 'newsletter/**/*.mjs'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
    },
  },
]
